### PR TITLE
Public suffix list custom URL and fallback file custom path

### PR DESCRIPTION
**Pull request by daareiza**
Added a few configuration options to the library (because I needed them):

- Option to set a custom URL for the public suffix list 
- Option to set a custom path for fallback file
- Option to include private domain list

Probably these options could help other users too.

_NOTE_: custom URL should be enclosed in single quotes.

### CODE REVIEW

**Comment by Zensavona** [comment]
Thanks @daareiza for the PR - much appreciated. The only issue is that the code which you've modified runs at build time rather than runtime - does it work as-is? (`domainatrex` defines all of these functions in a macro at build time as I am sure you've seen, this is to leverage pattern matching and make it much faster than similar libraries in other dynamic languages)

Other than that, just address the build failure and I am happy to merge.

**Comment by daareiza** [comment]
@Zensavona hi, yes, it is intended to be run at compile time and it works well, or at least for what I need :) .

About the build failure, I don't have too much experience with travis but let me take a look, it seems it's something related to the build process itself (wget is unable to fetch erlang), not the library tests.

**Comment by Zensavona** [comment]
Awesome, I’ll have a look at travis and see if I can make it build. Thanks for the improvement to the library :)

**Comment by daareiza** [comment]
@Zensavona fixed travis build, it seems now the default distro is Xenial, which doesn't supports Erlang 18.3, so I just forced the distro to be the previous default one, Trusty. Probably it would be a good idea to update the default elixir/erlang versions, also because of this warning:

`warning: the dependency :jason requires Elixir "~> 1.4" but you are running on v1.3.2`

Thanks!!!

**Comment by Zensavona** [comment]
@daareiza the changes are in v2.3.0 :)

**Pull request merged**
